distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Sun Mar 31 14:26:28 2019"
installation_id: "34123c6b-47be-4d9d-a12d-271d729f045a"
rime_version: 1.4.0